# Source: hdfs/charts/hdfs-client-k8s/templates/client-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-client
  labels:
    app: hdfs-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-client
  template:
    metadata:
      labels:
        app: hdfs-client
    spec:
      containers:
        - name: hdfs-client
          image: spark
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 18088
            name: http
          volumeMounts:
            - name: hdfs-config
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
              readOnly: true
            - name: hdfs-config-2
              mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
              readOnly: true
            - name: hdfs-config-3
              mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
              readOnly: true
            - name: hdfs-config-4
              mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
              readOnly: true
            - name: spark-claim
              mountPath: /opt/spark/oneslide
              subPath: oneslide

      volumes:
        - name: hdfs-config
          configMap:
            name: hdfs-config
            items:
              - key: core-site.xml
                path: core-site.xml
        - name: hdfs-config-2
          configMap:
            name: hdfs-config
            items:
              - key: hdfs-site.xml
                path: hdfs-site.xml
        - name: hdfs-config-3
          configMap:
            name: hdfs-config
            items:
              - key: mapred-site.xml
                path: mapred-site.xml
        - name: hdfs-config-4
          configMap:
            name: hdfs-config
            items:
              - key: yarn-site.xml
                path: yarn-site.xml
        - name: spark-claim
          persistentVolumeClaim:
            claimName: spark-claim
---
# Source: hdfs/charts/hdfs-namenode-k8s/templates/namenode-statefulset.yaml
# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  labels:
    app: spark-history-server
spec:
  ports:
  - port: 18080
    name: http
    nodePort: 31808
  type: NodePort
  selector:
    app: hdfs-client

